language: java
jdk:
  - openjdk11

script:
  - mvn clean install

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: target/your-artifact.jar
    skip_cleanup: true
    on:
      tags: true

  - provider: script
    script: mvn deploy -DskipTests --settings .travis/settings.xml
    skip_cleanup: true
    on:
      branch: main
      condition: "! $TRAVIS_TAG"

  - provider: script
    script: mvn deploy -DskipTests --settings .travis/settings.xml
    skip_cleanup: true
    on:
      tags: true
